### ISSUE TITLE
Example file 

### ISSUE THREAD

**Issue by brobee** [creditdatamw/zerocell#1]
Hi,

I do not understand this line of code. Maybe the code is not up to date, or should I implement such reader class for myself as well? I didn't find it in the example folder.

        ZeroCellReader<Person> reader = new com.creditdatamw.zerocell.example.PersonExcelReader();

Thanks

**Comment by zikani03** [comment]
Hello @brobee 

The Reader class is generated when you are using the annotation processor and the class is generated during compile time (that's why the repo doesn't have that class)

You don't have to use the annotation processor to use the library, but if you want to - add `@ZerocellReaderBuilder` to the class with the column annotations. The generated class will be placed in the same package as the class you place that annotation on. If you're using maven the generate file will be in `target/generated-sources/annotations`

I hope that helps

Regards,
Zikani
